version: '2'

services:
  web:
    container_name: veille.local-web
    build: ./php-apache
    ports:
      - 80:80
    links:
      - db
#      - memcached
    depends_on:
      - db
#      - memcached
#      - mongodb
    volumes:
      - ./../:/var/www/html
#      - ./php-apache/logs:/var/log/apache2
      - ./php-apache/vhosts/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
    extra_hosts:
      - 'veille.local:192.168.33.10'
  
  db:
    build: ./mysql
    container_name: veille.local-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: XXXX
    volumes:
      - ./mysql/db:/var/lib/mysql
  
 # mongodb:
 #   image: mongo:3.2.10
 #   container_name: mongodb
 #   ports:
 #     - "27017:27017"
 #   volumes:
 #     - ./mongodb:/var/lib/mongodb
 #   restart: always 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: veille.dev-phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
  
 # memcached:
 #   image: memcached:1.4.33
 #   container_name: memcached
 #   restart: always
 #   ports:
 #    - 11211:11211
 
volumes:
  src:
    driver: local
#  lib:
#    driver: local
  db:
    driver: local
 # mongodb:
 #   driver: local
  
